### ISSUE TITLE
Project status, further development/roadmap?

### ISSUE THREAD

**Issue by lucafaggianelli** [raphaellepuschitz/SVG-World-Map#2]
Hey @raphaellepuschitz just stumbled upon this project, it's really nice, are you looking forward to continue developing it and maybe packaging it into an installable package on NPM?

Happy to help you if you're interested, let me know!

**Comment by raphaellepuschitz** [comment]
Hi, 
thanks for your interest! 

Yes, I will continue the developemnt, but only as a side-project. So please be patient, if there's some time between version releases. 
Also, I plan to support Node.js and NPM, hopefully with some of the next versions. If I need help with it, I'll let you know - thank's for the offer! 

You can find the current roadmap in the README: https://github.com/raphaellepuschitz/SVG-World-Map/blob/master/README.md#further-development--changelog
